Task: T/22/005385
open-synergy/opnsynid-vertical-accountant pull request #148
Opened 2022-01-12 16:35 UTC by Asrulbastian

Pembuatan modul awal

2022-01-14 03:48 UTC, mikevhe18 requested changes

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/README.rst
> +5.  Search For *Quality Control for Accountant Report*
Stakeholder Report for Accountant Report

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/README.rst
> +This module is maintained by the OpenSynergy Indonesia.
.. image:: https://simetri-sinergi.id/logo.png
   :alt: PT. Simetri Sinergi Indonesia
   :target: https://simetri-sinergi.id.com

This module is maintained by the PT. Simetri Sinergi Indonesia.

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/__openerp__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
2022

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/__init__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
2022

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/menu.xml
> +     License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl). -->
2022

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/__init__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
2022

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
2022

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report.py
> +        comodel_name="accountant.report",
comodel_name -> accountant.report_stakeholder_report

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report.py
> +        column2="accountant_report_id",
column1 -> accountant_report_id
column2 -> stakeholder_report_id

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
2022

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +    )
Field akan **readonly** apabila state **_bukan_** **draft**

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +    )
Field akan **readonly** apabila state **_bukan_** **draft**

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +    )
Field akan **readonly** apabila state **_bukan_** **draft**

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +    )
Field akan **readonly** apabila state **_bukan_** **draft**

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +    )
Field akan **readonly** apabila state **_bukan_** **draft**

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +
Tambahkan confirm_ok

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +
tambahkan **valid_date** & **valid_user_id**

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +
Tambahkan 
```
    @api.multi
    def _compute_policy(self):
        _super = super(AccountantReportStakeholderReport, self)
        _super._compute_policy()
```

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +            "name": sequence,
Tambahkan 
```
"valid_date": fields.Datetime.now(),
"valid_user_id": self.env.user.id,
```

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +            "cancel_user_id": False,
Tambahkan
```
"valid_date": False,
"valid_user_id": False,
```

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +        return result
Tambahkan contrains untuk "Start Date cannot be greater than End Date"

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report_type.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
2022

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report_type.py
> +        relation="rel_stakeholder_report_confirm_group",
rel_stakeholder_report_type_confirm_group

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report_type.py
> +        relation="rel_stakeholder_report_cancel_group",
rel_stakeholder_report_type_cancel_group

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report_type.py
> +        relation="rel_stakeholder_report_restart_group",
rel_stakeholder_report_type_restart_group

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report_type.py
> +        relation="rel_stakeholder_report_restart_validation_group",
rel_stakeholder_report_type_restart_validation_group

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report_type.py
> +
tambahkan valid_grp_ids

2022-01-14 03:48 UTC, mikevhe18 commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_type_views.xml
> +                                <field name="cancel_grp_ids" widget="many2many_tags" />
tambahkan valid_grp_ids

2022-01-18 10:58 UTC, andhit-r requested changes

2022-01-18 10:58 UTC, andhit-r commented on accountant_report_stakeholder_report/models/accountant_report_stakeholder_report.py
> +class AccountantReportStakeholderReport(models.AbstractModel):
```suggestion
class AccountantReportStakeholderReport(models.Model):
```

@Asrulbastian @mikevhe18 ini gw yg salah desain. Jgn dibuat jd abstract, model biasa aja. Nanti obt turunannya akan seperti taxform_pph_common

2022-01-25 08:59 UTC, mikevhe18 requested changes

2022-01-25 08:59 UTC, mikevhe18 commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            </page>
Tambahkan Page Untuk Multiple Approval
```
<page string="Reviews" name="tier_validation">
    <group name="tier_validation_1" colspan="4" col="2">
        <field name="definition_id" />
        <field
                    name="reviewer_partner_ids"
                    widget="many2many_tags"
                />
    </group>
    <group name="tier_validation_2" colspan="4" col="2">
        <field name="review_ids" readonly="1" />
    </group>
</page>
```

2022-01-25 08:59 UTC, mikevhe18 commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +        />
Hapus

2022-01-25 10:35 UTC, Asrulbastian commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            </page>
done

2022-01-25 10:35 UTC, Asrulbastian commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +        />
done

2022-01-26 02:35 UTC, andhit-r requested changes
@Asrulbastian @mikevhe18 masih ada yang tidak sesuai dengan kesepakatan koding

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_type_views.xml
> +                <form>
* https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/master-data/header-form-view.html
* https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/master-data/smartbutton-form-view.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            <div name="header_1" class="oe_title" style="width: 500px;">
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/transaksi/field-name-form.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                    <field name="name" />
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/transaksi/field-display-name-tree.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                    </sheet>
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/transaksi/open-chatter-form.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            attrs="{'invisible': ['|',('state','!=','draft'),('confirm_ok','=',False)]}"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            type="object"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            type="object"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            attrs="{'invisible':['|',('state','!=','confirm'),('valid_ok','=',False)]}"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            attrs="{'invisible':['|',('state','!=','valid'),('cancel_ok','=',False)]}"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                            attrs="{'invisible':['|',('state','!=','cancel'),('restart_ok','=',False)]}"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                                icon="terp-check"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-01-26 02:35 UTC, andhit-r commented on accountant_report_stakeholder_report/views/accountant_report_stakeholder_report_views.xml
> +                                icon="terp-gtk-stop"
https://open-synergy.github.io/mdbook-odoo-development/kesepakatan-coding/object-general/konfirmasi-klik-tombol.html

2022-02-10 09:42 UTC, merged