Task: T/22/005594
open-synergy/opnsynid-vertical-accountant pull request #157
Opened 2022-03-31 16:32 UTC by Asrulbastian

* Pembuatan Modul Baru

2022-04-18 22:12 UTC, andhit-r requested changes
@Asrulbastian @mikevhe18

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/__manifest__.py
> +    "category": "Administration",
Buang

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/__manifest__.py
> +# pylint: disable=locally-disabled, manifest-required-author
Buang

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/data/policy_template_accountant_report_data.xml
> +    <field name="name">Standard: Accountant Report</field>
Cukup **Standard**

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/data/sequence_template_accountant_report_data.xml
> +    <field name="name">Standard: Accountant Report</field>
Cukup **Standard**

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/data/policy_template_accountant_report_data.xml
> +<data noupdate="0">
```suggestion
<data noupdate="1">
```

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/security/res_groups_data.xml
> +</odoo>
Group ini dibuang saja. Fungsinya sudah digantikan dengan **manual_number_ok**

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/security/ir_module_category_data.xml
> +</odoo>
Dibuang karena tidak jadi digunakan pada data group

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/views/accountant_report_method_views.xml
> +    <field name="name">Accountant Report method</field>
```suggestion
    <field name="name">Accountant Report Methods</field>
```

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/views/accountant_report_method_views.xml
> +        name="Accountant Report Method"
```suggestion
        name="Accountant Report Methods"
```

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/models/accountant_report.py
> +    _create_sequence_state = "finalize"
```suggestion
    _create_sequence_state = "valid"
```

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/models/accountant_report.py
> +    )
Buang

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/models/accountant_report.py
> +    )
Buang

2022-04-18 22:12 UTC, andhit-r commented on ssi_accountant_report/models/accountant_report.py
> +        return report
Buang

2022-04-19 15:53 UTC, Asrulbastian commented on ssi_accountant_report/__manifest__.py
> +    "category": "Administration",
done

2022-04-19 15:53 UTC, Asrulbastian commented on ssi_accountant_report/__manifest__.py
> +# pylint: disable=locally-disabled, manifest-required-author
done

2022-04-19 15:53 UTC, Asrulbastian commented on ssi_accountant_report/data/policy_template_accountant_report_data.xml
> +    <field name="name">Standard: Accountant Report</field>
Done

2022-04-19 15:53 UTC, Asrulbastian commented on ssi_accountant_report/data/sequence_template_accountant_report_data.xml
> +    <field name="name">Standard: Accountant Report</field>
done

2022-04-19 15:54 UTC, Asrulbastian commented on ssi_accountant_report/data/policy_template_accountant_report_data.xml
> +<data noupdate="0">
done

2022-04-19 15:54 UTC, Asrulbastian commented on ssi_accountant_report/security/res_groups_data.xml
> +</odoo>
done, file di buang

2022-04-19 15:54 UTC, Asrulbastian commented on ssi_accountant_report/security/ir_module_category_data.xml
> +</odoo>
done, file dibuang

2022-04-19 15:55 UTC, Asrulbastian commented on ssi_accountant_report/views/accountant_report_method_views.xml
> +    <field name="name">Accountant Report method</field>
done

2022-04-19 15:55 UTC, Asrulbastian commented on ssi_accountant_report/views/accountant_report_method_views.xml
> +        name="Accountant Report Method"
done

2022-04-19 15:55 UTC, Asrulbastian commented on ssi_accountant_report/models/accountant_report.py
> +    _create_sequence_state = "finalize"
done

2022-04-19 15:55 UTC, Asrulbastian commented on ssi_accountant_report/models/accountant_report.py
> +    )
done, hapus fields

2022-04-19 15:55 UTC, Asrulbastian commented on ssi_accountant_report/models/accountant_report.py
> +    )
done, hapus fields

2022-04-19 15:55 UTC, Asrulbastian commented on ssi_accountant_report/models/accountant_report.py
> +        return report
done

2022-04-19 16:09 UTC, Asrulbastian commented on ssi_accountant_report/__manifest__.py
> +    "category": "Administration",
version dibutuhkan pada saat commit..

![Screenshot from 2022-04-19 23-09-32](https://user-images.githubusercontent.com/62274841/164047933-77c8244c-b4af-4cae-bf2e-9c047e8e88b0.png)

2022-04-20 00:43 UTC, andhit-r commented on ssi_accountant_report/__manifest__.py
> +    "category": "Administration",
@Asrulbastian yang dibuat **category** bukan version

2022-06-25 10:25 UTC, closed without merging