8.0 t003582
open-synergy/opnsynid-vertical-accountant pull request #93
Opened 2021-07-28 01:57 UTC by azmimr67

2021-07-30 09:40 UTC, andhit-r requested changes

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1101/data/ir_sequence_data.xml
> +        <field name="name">Accountant General Audit Index A1101</field>
General Audit Index A1101

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1101/data/ir_sequence_data.xml
> +        <field name="name">Accountant General Audit Index A1101</field>
General Audit Index A1101

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/__openerp__.py
> +        "base_cancel_reason",
Hapus karena dependensi ini sudah ada di accountant_general_audit. Tidak perlu disebutkan ulang.

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/__openerp__.py
> +        "web_readonly_bypass",
Hapus karena dependensi ini sudah ada di accountant_general_audit. Tidak perlu disebutkan ulang.

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/README.rst
> +Accountant General Audit Index A1102
General Audit Index A1102

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/README.rst
> +5.  Search For *Accountant General Audit Index A1102*
General Audit Index A1102

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/data/base_sequence_configurator_data.xml
> +            >result = document.account_type_set_id.accountant_general_audit_index_a1102_sequence_id</field>
result = document.account_type_set_id.index_a1102_sequence_id

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/data/ir_sequence_data.xml
> +        <field name="name">Accountant General Audit Index A1102</field>
General Audit Index A1102

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/data/ir_sequence_data.xml
> +        <field name="name">Accountant General Audit Index A1102</field>
General Audit Index A1102

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/models/accountant_client_account_type_set.py
> +    accountant_general_audit_index_a1102_sequence_id = fields.Many2one(
index_a1102_sequence_id

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/models/accountant_client_account_type_set.py
> +        string="Accountant General Audit Index 1102 Sequence",
Index 1102 Sequence

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +    _description = "Accountant General Audit Index A1102"
General Audit Index A1102

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +        store=False,
store=True

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +        related="general_audit_id.company_id",
store=True

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +        required=True,
required=False
store=True

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102_status.py
> +    _description = "Accountant General Audit IndexA1102 Status"
Index A1102 Status

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/security/ir_module_category_data.xml
> +    <field name="name">Accountant General Audit Index A1102 Usability</field>
General Audit Index A1102 Usability

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_client_account_type_set_views.xml
> +                <field name="accountant_general_audit_index_a1102_sequence_id" />
index_a1102_sequence_id

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                <field name="sequence" widget="handle" />
Pindahkan ke urutan pertama. widget handle yang bisa bekerja apabila diletakan pertama

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                <field name="note" />
Hapus. Field berjenis text secara default tidak diletakan di tree karena kemungkinan akan terlalu panjang

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                        <field name="sequence" />
Selalu tambahkan notebook walaupun kosong

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                        <field name="note" />
Note selalu diletakan di page tersendiri di notebook

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +        <field name="name">General Audit Index A1102 Status</field>
Index A1102 Status

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                    />
Hapus. Filter ini hanya berguna apabila obj diinherit dari ir.need.action

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                        />
Group berdasarkan general_audit_id

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                    fonts="bold:message_unread==True"
Hapus. Filter ini hanya berguna apabila obj diinherit dari ir.need.action

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                <field name="message_unread" invisible="1" />
Hapus. Filter ini hanya berguna apabila obj diinherit dari ir.need.action

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                <field name="name" />
display_name, bukan name. Apabila menggunakan name maka jika data belum pernah divalidasi yg tampil adalah /. Jika pakai display_name maka yg tampil adalah *ID. Dengan begitu jika klien mau merefer pada data yang belum diapprove maka tidak sulit.

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                <field name="partner_id" />
Pindahkan setelah display_name

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                            <field name="status_id" />
status_id pindahkan di tab question. Lihat layout di A1101 sebagai rujukan

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +            name="General Audit Index A1102"
Index A1102

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +            parent="accountant_general_audit.accountant_general_audit_menu"
accountant_general_audit.accountant_risk_assessment_menu

2021-07-30 09:40 UTC, andhit-r commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +            sequence="4"
2

2021-07-30 09:42 UTC, andhit-r requested changes
Review lihat di komen yah @azmimr67

2021-08-05 09:46 UTC, azmimr67 commented on accountant_general_audit_index_a1102/__openerp__.py
> +        "base_cancel_reason",
done

2021-08-05 09:46 UTC, azmimr67 commented on accountant_general_audit_index_a1102/__openerp__.py
> +        "web_readonly_bypass",
done

2021-08-05 09:47 UTC, azmimr67 commented on accountant_general_audit_index_a1102/README.rst
> +Accountant General Audit Index A1102
done

2021-08-05 09:47 UTC, azmimr67 commented on accountant_general_audit_index_a1102/README.rst
> +5.  Search For *Accountant General Audit Index A1102*
done

2021-08-05 09:49 UTC, azmimr67 commented on accountant_general_audit_index_a1102/data/base_sequence_configurator_data.xml
> +            >result = document.account_type_set_id.accountant_general_audit_index_a1102_sequence_id</field>
done

2021-08-05 09:50 UTC, azmimr67 commented on accountant_general_audit_index_a1102/data/ir_sequence_data.xml
> +        <field name="name">Accountant General Audit Index A1102</field>
done

2021-08-05 09:50 UTC, azmimr67 commented on accountant_general_audit_index_a1102/data/ir_sequence_data.xml
> +        <field name="name">Accountant General Audit Index A1102</field>
done

2021-08-05 09:50 UTC, azmimr67 commented on accountant_general_audit_index_a1102/models/accountant_client_account_type_set.py
> +    accountant_general_audit_index_a1102_sequence_id = fields.Many2one(
done

2021-08-05 09:51 UTC, azmimr67 commented on accountant_general_audit_index_a1102/models/accountant_client_account_type_set.py
> +        string="Accountant General Audit Index 1102 Sequence",
done

2021-08-05 09:52 UTC, azmimr67 commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +    _description = "Accountant General Audit Index A1102"
done

2021-08-05 09:52 UTC, azmimr67 commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +        store=False,
done

2021-08-05 09:53 UTC, azmimr67 commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +        related="general_audit_id.company_id",
done

2021-08-05 09:53 UTC, azmimr67 commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py
> +        required=True,
done

2021-08-05 09:54 UTC, azmimr67 commented on accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102_status.py
> +    _description = "Accountant General Audit IndexA1102 Status"
done

2021-08-05 09:55 UTC, azmimr67 commented on accountant_general_audit_index_a1102/security/ir_module_category_data.xml
> +    <field name="name">Accountant General Audit Index A1102 Usability</field>
done

2021-08-05 09:55 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_client_account_type_set_views.xml
> +                <field name="accountant_general_audit_index_a1102_sequence_id" />
done

2021-08-05 09:56 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                <field name="sequence" widget="handle" />
done

2021-08-05 09:57 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                <field name="note" />
done

2021-08-05 10:00 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                        <field name="sequence" />
done

2021-08-05 10:00 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +                        <field name="note" />
done

2021-08-05 10:01 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_status_views.xml
> +        <field name="name">General Audit Index A1102 Status</field>
done

2021-08-05 10:02 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                    />
done

2021-08-05 10:03 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                        />
done

2021-08-05 10:05 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                <field name="partner_id" />
Ini kan di tree?

2021-08-05 10:08 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +                            <field name="status_id" />
done

2021-08-05 10:09 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +            name="General Audit Index A1102"
done

2021-08-05 10:10 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +            parent="accountant_general_audit.accountant_general_audit_menu"
done

2021-08-05 10:10 UTC, azmimr67 commented on accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml
> +            sequence="4"
done

2021-10-11 14:44 UTC, closed without merging