8.0 t003583 new
open-synergy/opnsynid-vertical-accountant pull request #98
Opened 2021-08-06 04:08 UTC by azmimr67

2021-08-09 09:41 UTC, andhit-r requested changes
Jangan lupa tambahkan:
1. accountant_general_audit.py https://github.com/open-synergy/opnsynid-vertical-accountant/blob/8.0/accountant_general_audit_index_a1102/models/accountant_general_audit.py . Sesuaikan isinya
2. accountant_general_audit_views.xml https://github.com/open-synergy/opnsynid-vertical-accountant/blob/8.0/accountant_general_audit_index_a1102/views/accountant_general_audit_views.xml

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/README.rst
> +General Audit Index A1104
A.110.4

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/README.rst
> +5.  Search For *General Audit Index A1104*
A.110.4

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/__openerp__.py
> +    "name": "General Audit Index A1104",
A.110.4

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/data/base_sequence_configurator_data.xml
> +            id="base_sequence_accountant_general_audit_index_a1104"
XML ID tidak boleh sama dengan XML ID sequence

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    _description = "General Audit Index A1104"
A.110.4

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +
Tambahkan method **_compute_general_audit_id**. Lihat contoh di https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py#L35

Tambahkan method **_inverse_general_audit**. Contoh lihat di https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py#L45 .

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    )
Sesuaikan **general_audit_id** sesuai dengan https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py#L63-L75

Tambahkan **general_audit_ids**. Lihat contoh di https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py#L76-L82. Sesuaikan **relation** dan **column1**

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +        required=True,
Buang

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +        required=False,
Buang

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    )
Tambahkan https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py#L103-L148

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    )
Tambahkan https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/models/accountant_general_audit_index_a1102.py#L285-L292

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104_status.py
> +    _description = "Index A1104 Status"
A.110.4

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_status_views.xml
> +            name="Index A1104 Status"
A.110.4

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_status_views.xml
> +            parent="accountant_general_audit.accountant_configuration_general_audit_menu"
accountant_general_audit.accountant_configuration_general_audit_menu

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                        />
Tambahkan https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml#L78-L115

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                    fonts="bold:message_unread==True"
Hapus krn obj tidak depend ke ir.need.action

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                <field name="message_unread" invisible="1" />
Hapus krn obj tidak depend ke ir.need.action

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                        </group>
Sesuaikan dengan https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml#L250-L277

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                                </group>
Sesuaikan dengan https://github.com/open-synergy/opnsynid-vertical-accountant/blob/423736d889e47992957e785851863937fc9b657c/accountant_general_audit_index_a1102/views/accountant_general_audit_index_a1102_views.xml#L318-L321

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +        <field name="name">General Audit Index A1104</field>
A.110.4

2021-08-09 09:41 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +            name="Index A1104"
A.110.4

2021-08-13 04:01 UTC, azmimr67 commented on accountant_general_audit_index_a1104/README.rst
> +General Audit Index A1104
done

2021-08-13 04:01 UTC, azmimr67 commented on accountant_general_audit_index_a1104/README.rst
> +5.  Search For *General Audit Index A1104*
done

2021-08-13 04:02 UTC, azmimr67 commented on accountant_general_audit_index_a1104/__openerp__.py
> +    "name": "General Audit Index A1104",
done

2021-08-13 04:10 UTC, azmimr67 commented on accountant_general_audit_index_a1104/data/base_sequence_configurator_data.xml
> +            id="base_sequence_accountant_general_audit_index_a1104"
done

2021-08-13 04:11 UTC, azmimr67 commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    _description = "General Audit Index A1104"
done

2021-08-13 04:22 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                <field name="message_unread" invisible="1" />
done

2021-08-13 04:24 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                        </group>
done

2021-08-13 04:25 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                                </group>
done

2021-08-13 04:26 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +        <field name="name">General Audit Index A1104</field>
done

2021-08-13 04:27 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +            name="Index A1104"
done

2021-08-13 09:28 UTC, andhit-r requested changes

2021-08-13 09:28 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    )
@azmimr67 , ini masih ketinggalan

2021-08-13 09:28 UTC, andhit-r commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104_status.py
> +    _description = "Index A1104 Status"
Masih ketinggalan

2021-08-13 09:28 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                        />
Masih ketinggalan

2021-08-13 09:28 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                    </group>
Samakan dengan https://github.com/open-synergy/opnsynid-vertical-accountant/blob/08dbedbc02d973c7af3d92897cf1dc47f49dfa0c/accountant_general_audit_index_a1101/views/accountant_general_audit_index_a1101_views.xml#L250-L277

2021-08-13 09:28 UTC, andhit-r commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +            sequence="4"
1104

2021-08-14 10:14 UTC, azmimr67 commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104_status.py
> +    _description = "Index A1104 Status"
done

2021-08-14 10:15 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_status_views.xml
> +            name="Index A1104 Status"
done

2021-08-14 10:16 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_status_views.xml
> +            parent="accountant_general_audit.accountant_configuration_general_audit_menu"
done

2021-08-14 10:20 UTC, azmimr67 commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    )
done

2021-08-14 10:21 UTC, azmimr67 commented on accountant_general_audit_index_a1104/models/accountant_general_audit_index_a1104.py
> +    )
done

2021-08-14 10:21 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_status_views.xml
> +            parent="accountant_general_audit.accountant_configuration_general_audit_menu"
done

2021-08-14 10:24 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                        />
done

2021-08-14 10:35 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +                    </group>
done

2021-08-14 10:37 UTC, azmimr67 commented on accountant_general_audit_index_a1104/views/accountant_general_audit_index_a1104_views.xml
> +            sequence="4"
done

2021-08-17 04:30 UTC, merged